name: rokugtk
version: 0.3.0
summary: A Roku remote for Gtk
description: Control your Roku or Now TV box on your desktop or laptop
confinement: strict
grade: stable

apps:
  rokugtk:
    command: bin/wrapper
    plugs: [network-bind, network-control, x11]

parts:
  cliftonts:
    plugin: python
    source: .
    python-version: python2
    stage-packages:
      - fontconfig-config
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
      - python-gtk2
      - python-requests
    organize:
      ../build/wrapper: bin/
      ../build/rokugtk.png: bin/
      ../build/rokugtk.py: bin/
    after:
      - desktop-gtk2
    # install: |
    #   mkdir -p $SNAPCRAFT_PART_INSTALL/bin
    #   cp rokugtk.py $SNAPCRAFT_PART_INSTALL/bin/
#      chmod a+x $SNAPCRAFT_PART_INSTALL/bin/rokugtk.py
