name: rokugtk
version: 0.0.1
summary: A Roku remote for Gtk
description: Control your Roku or Now TV box on your desktop or laptop
confinement: strict
grade: devel

apps:
  rokugtk:
    command: bin/wrapper
    plugs: [network-bind, x11]

parts:
  cliftonts:
    plugin: python
    source: .
    python-version: python2
    stage-packages:
      - fontconfig-config
      - fonts-dejavu-extra
      - fonts-ipafont-gothic
      - python-gtk2
      - python-requests
    organize:
      ../build/wrapper: bin/
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp rokugtk.py $SNAPCRAFT_PART_INSTALL/bin/
#      chmod a+x $SNAPCRAFT_PART_INSTALL/bin/rokugtk.py
